#!/usr/bin/env python3
#
# convert pnm scans to reasonably-sized PDFs.

from convert import Options
from convert import PDFWorkQueue

if __name__ == "__main__":
    options = Options(Options.get_argument_parser().parse_args())
    print("Running convert-scans.\n")
    print(options)
    wq = PDFWorkQueue(options)
    wq.run()
    print("Done. Check {:s}".format(options.general.pdfname))

# Local Variables:
# mode: python
# End:
