#!/usr/bin/env python3
#
# drop pages from a PDF

from pages import PageDropper

if __name__ == "__main__":
    print("Running drop-pages...")
    page_drop = PageDropper(PageDropper.get_argument_parser().parse_args())
    print(page_drop.options)
    page_drop.run()

# Local Variables:
# mode: python
# End:
