#!/usr/bin/env python3
#

from compliance import MakePDFCompliant

if __name__ == "__main__":
    print("Running make-comply...")
    make_comply = MakePDFCompliant()
    make_comply.parse_args()
    print(make_comply.options)
    make_comply.run()

# Local Variables:
# mode: python
# End:
